# Generated by Django 3.2.5 on 2021-09-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='project-thumbnails')),
                ('description', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
    ]
