# Generated by Django 3.2.5 on 2021-10-03 03:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210926_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, quality=100, size=[160, 90], upload_to='author-pfp'),
        ),
    ]
