# Generated by Django 3.2.5 on 2021-10-03 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_author_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='points',
        ),
        migrations.AddField(
            model_name='post',
            name='points',
            field=models.ManyToManyField(related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
