# Generated by Django 3.2.5 on 2021-10-03 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20211004_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='points',
        ),
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.ManyToManyField(related_name='post_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(related_name='post_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
