# Generated by Django 3.2.5 on 2021-10-07 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211005_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(related_name='followers', to='blog.Author')),
                ('following', models.ManyToManyField(related_name='following', to='blog.Author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
        ),
    ]
