# Generated by Django 3.2.5 on 2021-10-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_authormeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormeta',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='authormeta',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to='blog.Author'),
        ),
    ]
