# Generated by Django 3.2.5 on 2021-10-07 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211007_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormeta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
